application: gopushservice
version: 1
runtime: go
api_version: go1

handlers:
- url: /admin
  script: _go_app
  login: admin
  secure: always
- url: /.*
  script: _go_app
  secure: always
- url: /_ah/remote_api
  script: _go_app
  login: admin